class LoadingPlace:  
    def __init__(self, index, CODCENTCUS, LATITUDE_FILIAL, LONGITUDE_FILIAL):  
        self.index = index
        self.CODCENTCUS = CODCENTCUS 
        self.LATITUDE_FILIAL = LATITUDE_FILIAL 
        self.LONGITUDE_FILIAL = LONGITUDE_FILIAL 

class MixerTruck:  
    def __init__(self, index, CODVEICULO, CODCENTCUS, LATITUDE_FILIAL, LONGITUDE_FILIAL):  
        self.index = index
        self.CODVEICULO = CODVEICULO 
        self.CODCENTCUS = CODCENTCUS 
        self.LATITUDE_FILIAL = LATITUDE_FILIAL 
        self.LONGITUDE_FILIAL = LONGITUDE_FILIAL 

class Order:  
    def __init__(self, CODPROGRAMACAO, CODCENTCUS, MEDIA_M3_DESCARGA, VALTOTALPROGRAMACAO, 
        LATITUDE_OBRA, LONGITUDE_OBRA, LATITUDE_FILIAL, LONGITUDE_FILIAL):  
        self.CODPROGRAMACAO = CODPROGRAMACAO 
        self.CODCENTCUS = CODCENTCUS 
        self.MEDIA_M3_DESCARGA = MEDIA_M3_DESCARGA 
        self.VALTOTALPROGRAMACAO = VALTOTALPROGRAMACAO 
        self.LATITUDE_OBRA = LATITUDE_OBRA
        self.LONGITUDE_OBRA = LONGITUDE_OBRA
        self.LATITUDE_FILIAL = LATITUDE_FILIAL 
        self.LONGITUDE_FILIAL = LONGITUDE_FILIAL 

class Delivery:  
    def __init__(self, VLRVENDA, HORCHEGADAOBRA, CODPROGRAMACAO, CODPROGVIAGEM, CODCENTCUSVIAGEM, 
        VLRTOTALNF, VALVOLUMEPROG, CUSVAR, CODTRACO, LATITUDE_OBRA, LONGITUDE_OBRA):  
        self.VLRVENDA = VLRVENDA
        self.HORCHEGADAOBRA = HORCHEGADAOBRA
        self.CODPROGRAMACAO = CODPROGRAMACAO 
        self.CODPROGVIAGEM = CODPROGVIAGEM 
        self.CODCENTCUSVIAGEM = CODCENTCUSVIAGEM 
        self.VLRTOTALNF = VLRTOTALNF 
        self.VALVOLUMEPROG = VALVOLUMEPROG
        self.CODTRACO = CODTRACO
        self.CUSVAR = CUSVAR
        self.LATITUDE_OBRA = LATITUDE_OBRA
        self.LONGITUDE_OBRA = LONGITUDE_OBRA
